### ISSUE TITLE
Js language plugin - "enable_multi_threading" support 

### ISSUE THREAD

**Issue by bimalviswam** [getgauge/gauge-js#191]
Currently js plugin does not have multithreading capability. For each stream it spins up separate suite which cause trouble especially in integrations with other tools. 

Take a scenario :  Automation suite is integrated with any test management tool and if test run needs to be automatically created for every execution inside the test management tool. In this case, right now the only option available is to create the suite outside gauge . Because , if the create suite code is even at the the highest level of hooks , which is before suite, multiple suites will be created which is incorrect. Ideally only 1 suite should be created for the entire run.

**Comment by zabil** [comment]
I am finding it very hard to understand the problem and it's connection to multi threading.

As far as I know node and javascript does not support multi threading. There are webworkers In node 10+ but it's still experimental.

**Comment by bimalviswam** [comment]
Here is the sample project  - 

[https://github.com/bimalviswam/GaugeSample](https://github.com/bimalviswam/GaugeSample)

If I run the project using "gauge run specs -p" , the code in the before suite is executed twice. I wanted that to happen only once. If not in "beforesuite" , where else I can place that piece of code that it only executes once, and not per parallel steams . My expectation was that the before suite code will execute before even starting the parallel streams.  

Here is what I am trying to do : Create a testSuite in the test management tool- TestRail before starting the execution, and update the results automatically. So for each run, regardless of using parallel execution, I should I only see 1 suite with all the test cases and results. Currently I could not find a place for this piece of code .

**Comment by sriv** [comment]
I _think_ I understand @bimalviswam's concern.

When `gauge run -p specs` is invoked (note the `-p` flag), gauge attempts to run the specs in parallel, and when the implementation is in javascript, gauge spawns off as many `gauge-js` child processes as the number of streams.

The drawback is that since these are independent processes, the `BeforeSuite` and `AfterSuite` hooks are executed once per stream (there is no easy way to share state across processes) and this can be a problem when the code implementation assumes a run-once behaviour.

Some options:

- let `gauge-js`run steps as async such that step execution is non-blocking, and allow `gauge-js` to multiplex execution requests from gauge.

- consider exploring libraries such as [napajs](https://github.com/Microsoft/napajs) or [paralleljs](https://parallel.js.org/) to enable multithreading behaviour.

**Comment by Apoorva-GA** [comment]
In order to enable multithreading, one has to set `enable_multithreading = true` in default.properties file and run the specs in parallel.

**Comment by Debashis9012** [comment]
Based on the above observation this feature has been verified and found fixed.
Tested version: ```2.3.5.nightly-2019-05-15 ```

**Comment by WilliamPenado** [comment]
Hello!
Is there any new information regarding this issue?, I still am facing the problem where the @BeforeSuite and @AfterSuite annotations execute once per each specification instead of once before all specifications

Thank you.
Regards.

**Comment by bimalviswam** [comment]
I dont think the actual problem is fixed here. As per @Apoorva-GA , the problem is still there where each connection will execute the beforeSuite and afterSuite hooks. Ideally what we need is a hook which will execute only once regardless of if the specs are run parallel or sequential.

@zabil

**Comment by nehashri** [comment]
@bimalviswam @WilliamPenado  The hooks are run for each connection intentionally. If multithreading is not enabled, each connection is a separate process and since, data is not shared between the processes, setup steps may need to be done in each process.
However, with multi threading, now you can control the execution of hooks programmatically. A simple if condition with a flag is one way to get your hook to run only once.

**Comment by bimalviswam** [comment]
Facing a challenge with "enable_multithreading = true"  . Here is my
project - https://github.com/bimalviswam/GaugeSample .

With "enable_multithreading = true",  I get the following error
inconsistently . It seems that driver instances are mixed up while in run
and the wrong driver is killed due to this .  This code runs parallel with
out any issues with multithreading set to false . Am I missing some basic
concepts here?

*Error Message: NoSuchSessionError: This driver instance does not have a
valid session ID (did you call WebDriver.quit()?) and may no longer be
used.*

**Comment by WilliamPenado** [comment]
Hi @nehashri,

That's what I thought when I switched the multithreading flag to true in the default.properties file; however, even thought I can to execute my automated test scripts without any issues in parallel, I am not able to properly use the @BeforeSuite tag as I expect, Gauge fires the code within the method tagged with @BeforeSuite before every single specification and not a single time before the whole suite.

I am trying to look for a work around to achieve what I need to. If you can think of any other troubleshooting I can perform I will appreciate it.

Thanks,

**Comment by bimalviswam** [comment]
Any thoughts to the challenge that we are facing?

**Comment by BugDiver** [comment]
@bimalviswam I spend some time figuring out your issue. The problem is with code which you are using to open and close the browser in `CommonUtils.js`.

Since there is no threading in javascript, all of your code is run in a single thread.

In your case, when the `beforeScenario` is called for the first time it creates a driver and put it as `this.driver` in `CommonUtils`. but when it's called second time (for the second scenario or spec) it again creates a new driver and assigns it to the same `this.driver`.
Now the first call to `afterScenario` will actually close the second driver instance, and the second scenario will error out because the driver instance is closed.

One way to deal with this is to store the driver in datastores (in your case scenario data store).

**Comment by bimalviswam** [comment]
Do we have scenario data store available in before scenario Hook? I tried
and  dont think its.

**Comment by BugDiver** [comment]
Might be related to https://github.com/getgauge/gauge-js/issues/227

**Comment by singhverse** [comment]
> @bimalviswam @WilliamPenado The hooks are run for each connection intentionally. If multithreading is not enabled, each connection is a separate process and since, data is not shared between the processes, setup steps may need to be done in each process. However, with multi threading, now you can control the execution of hooks programmatically. A simple if condition with a flag is one way to get your hook to run only once.

Hi @nehashri , do you have a sample code block that demonstrates how to programmatically limit the number of time @beforeSuite/@afterSuite hooks are executed in parallel execution?

Thanks.
